### ISSUE TITLE
Learboard Error

### ISSUE THREAD

**Issue by zoomiebr** [erpk/harvester#40]
Error Message

```Fatal error: Uncaught exception 'XPathSelector\Exception\NodeNotFoundException' with message 'Query //a[@class="user_avatar"][1] returned no results' in C:\xampp\htdocs\hue\vendor\stil\xpath-selector\src\Node.php:52 Stack trace: #0 C:\xampp\htdocs\hue\vendor\erpk\harvester\src\Module\Login\LoginModule.php(42): XPathSelector\Node->find('//a[@class="use...') #1 C:\xampp\htdocs\hue\vendor\erpk\harvester\src\Client\Client.php(182): Erpk\Harvester\Module\Login\LoginModule->login() #2 C:\xampp\htdocs\hue\vendor\erpk\harvester\src\Client\Client.php(193): Erpk\Harvester\Client\Client->login() #3 C:\xampp\htdocs\hue\vendor\erpk\harvester\src\Module\Military\Leaderboard.php(132): Erpk\Harvester\Client\Client->checkLogin() #4 C:\xampp\htdocs\hue\learboard_div2.php(35): Erpk\Harvester\Module\Military\Leaderboard->citizensDamage() #5 {main} thrown in C:\xampp\htdocs\hue\vendor\stil\xpath-selector\src\Node.php on line 52```

**Comment by stil** [comment]
This error indicates problems with logging in, not with leaderboards. Make sure you set right password.
